# Generated by Django 3.1.7 on 2021-04-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeeksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geeks_field', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='lection',
            name='body',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lection',
            name='title',
            field=models.CharField(default='DELETE', max_length=255),
        ),
    ]
