# Generated by Django 3.1.7 on 2021-04-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_lection_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='lection',
            name='open_time',
            field=models.DateField(default=None),
        ),
    ]
