# Generated by Django 3.1.7 on 2021-04-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_lection_open_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lection',
            name='body',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='lection',
            name='document',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='lection',
            name='open_time',
            field=models.DateTimeField(default=None),
        ),
    ]
