# Generated by Django 3.1.7 on 2021-04-01 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210401_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lection',
            name='open_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
