# Generated by Django 3.1.7 on 2021-04-01 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_newuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='TestUser',
        ),
    ]
