# Generated by Django 3.1.7 on 2021-04-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210401_2230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Practices',
            new_name='Practice',
        ),
    ]
