# Generated by Django 3.1.7 on 2021-05-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210522_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('default', 'default'), ('extended', 'extended'), ('input', 'input')], default=('input', 'input'), max_length=10),
        ),
    ]
