# Generated by Django 3.1.7 on 2021-05-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='sroce_value_per_type_1',
            field=models.PositiveSmallIntegerField(default=0, help_text='Value per 1 RIGHT answer'),
        ),
        migrations.AddField(
            model_name='test',
            name='sroce_value_per_type_2',
            field=models.PositiveSmallIntegerField(default=0, help_text='Value per 1 RIGHT answer'),
        ),
        migrations.AddField(
            model_name='test',
            name='sroce_value_per_type_3',
            field=models.PositiveSmallIntegerField(default=0, help_text='Value per 1 RIGHT answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('default', 'default'), ('extended', 'extended'), ('input', 'input')], default=('default', 'default'), max_length=10),
        ),
    ]
