# Generated by Django 3.1.7 on 2021-05-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210522_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='sroce_value_per_type_1',
            field=models.PositiveSmallIntegerField(default=1, help_text='Value per 1 RIGHT answer'),
        ),
        migrations.AlterField(
            model_name='test',
            name='sroce_value_per_type_2',
            field=models.PositiveSmallIntegerField(default=1, help_text='Value per 1 RIGHT answer'),
        ),
        migrations.AlterField(
            model_name='test',
            name='sroce_value_per_type_3',
            field=models.PositiveSmallIntegerField(default=1, help_text='Value per 1 RIGHT answer'),
        ),
    ]
