# Generated by Django 3.1.7 on 2021-05-23 04:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210523_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, default=None, null=True, upload_to='upload/sfiles/')),
                ('passed_time', models.DateTimeField(default=datetime.datetime.now)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.practice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practiceresults', to='main.student')),
            ],
        ),
    ]
